version: '2'
services:
  my_simple_shop-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/my_simple_shop/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_simple_shop
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
